import { createClient } from '@/utils/supabase/server'
import { ShieldAlert, ArrowLeft } from '@/components/Icons'
import Link from 'next/link'

export default async function SecurityLogsPage() {
  const supabase = await createClient()

  // Fetch used invite tokens as an audit trail
  const { data: tokens } = await supabase
    .from('invite_tokens')
    .select('email, role, full_name, created_at, expires_at, used_at')
    .order('created_at', { ascending: false })
    .limit(100)

  return (
    <div className="space-y-6">
      <div>
        <Link href="/admin/dashboard/settings" className="inline-flex items-center text-blue-600 hover:text-blue-700 text-sm font-medium mb-4 transition-colors">
          <ArrowLeft className="w-4 h-4 mr-1" /> Back to Settings
        </Link>
        <h1 className="text-3xl font-playfair font-bold text-slate-900 flex items-center">
          <ShieldAlert className="w-8 h-8 mr-3 text-red-600" />
          Security Logs
        </h1>
        <p className="text-slate-500 mt-1">Track all portal invite activity and account creation events.</p>
      </div>

      {/* Summary Stats */}
      <div className="grid grid-cols-3 gap-4">
        <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-4 text-center">
          <p className="text-2xl font-bold text-slate-900">{tokens?.length ?? 0}</p>
          <p className="text-sm text-slate-500 mt-1">Total Invites Sent</p>
        </div>
        <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-4 text-center">
          <p className="text-2xl font-bold text-emerald-600">{tokens?.filter(t => t.used_at).length ?? 0}</p>
          <p className="text-sm text-slate-500 mt-1">Accepted</p>
        </div>
        <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-4 text-center">
          <p className="text-2xl font-bold text-amber-600">{tokens?.filter(t => !t.used_at && new Date(t.expires_at) > new Date()).length ?? 0}</p>
          <p className="text-sm text-slate-500 mt-1">Pending</p>
        </div>
      </div>

      {/* Invite Log Table */}
      <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden">
        <div className="p-4 border-b border-slate-100">
          <h2 className="font-semibold text-slate-900">Invite Activity Log</h2>
          <p className="text-xs text-slate-500 mt-0.5">All portal invites generated by administrators.</p>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-sm text-left">
            <thead>
              <tr className="bg-slate-50 border-b border-slate-200">
                <th className="py-3 px-4 font-semibold text-slate-700">Name</th>
                <th className="py-3 px-4 font-semibold text-slate-700">Email</th>
                <th className="py-3 px-4 font-semibold text-slate-700">Role</th>
                <th className="py-3 px-4 font-semibold text-slate-700">Sent</th>
                <th className="py-3 px-4 font-semibold text-slate-700">Expires</th>
                <th className="py-3 px-4 font-semibold text-slate-700">Status</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {tokens && tokens.length > 0 ? tokens.map((token, i) => {
                const isExpired = !token.used_at && new Date(token.expires_at) < new Date()
                const isAccepted = !!token.used_at
                const isPending = !token.used_at && !isExpired

                return (
                  <tr key={i} className="hover:bg-slate-50">
                    <td className="py-3 px-4 font-medium text-slate-900">{token.full_name}</td>
                    <td className="py-3 px-4 text-slate-600">{token.email}</td>
                    <td className="py-3 px-4">
                      <span className="px-2 py-0.5 bg-blue-50 text-blue-700 text-xs font-bold rounded-full capitalize">
                        {token.role?.replace('_', ' ')}
                      </span>
                    </td>
                    <td className="py-3 px-4 text-slate-500 text-xs">
                      {new Date(token.created_at).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
                    </td>
                    <td className="py-3 px-4 text-slate-500 text-xs">
                      {new Date(token.expires_at).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
                    </td>
                    <td className="py-3 px-4">
                      {isAccepted && (
                        <span className="px-2 py-0.5 bg-emerald-100 text-emerald-700 text-xs font-bold rounded-full">✓ Accepted</span>
                      )}
                      {isPending && (
                        <span className="px-2 py-0.5 bg-amber-100 text-amber-700 text-xs font-bold rounded-full">⏳ Pending</span>
                      )}
                      {isExpired && (
                        <span className="px-2 py-0.5 bg-red-100 text-red-600 text-xs font-bold rounded-full">✗ Expired</span>
                      )}
                    </td>
                  </tr>
                )
              }) : (
                <tr>
                  <td colSpan={6} className="py-12 text-center text-slate-400 italic">No invite activity found.</td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  )
}
